# app.yaml = application config file
application: pup-dbms-m4-4v2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app

- url: /_ah/login_required
  script: do_openid_login.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
